flags:
extra-package-dbs: []
packages:
- opentracing
- opentracing-cloudtrace
- opentracing-examples
- opentracing-http-client
- opentracing-jaeger
- opentracing-wai
- opentracing-zipkin-common
- opentracing-zipkin-v1
- opentracing-zipkin-v2
allow-newer: true # required for thrift
extra-deps:
- thrift-0.10.0
- optparse-applicative-0.14.0.0
- vinyl-0.12.1
resolver: lts-15.5
